name: Python Package using Conda

on:
  push:
    branch:
      - main
      - dev

permissions: read-all

jobs:
  predict:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Download required ml files
      run: |
        wget https://github.com/maxisoft/github-activity-predictor/releases/download/v0.1.0/model.pth -O model.pth
        wget https://github.com/maxisoft/github-activity-predictor/releases/download/v0.1.0/scalers.pkl.z -O scalers.pkl.z
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-activate-base: true
        activate-environment: ""
    - name: Install dependencies
      run: |
        conda install pip
        conda install pytorch cpuonly -c pytorch
        conda install numpy pandas scipy scikit-learn tqdm
        conda install --file requirements.txt
    - name: Lint with flake8
      run: |
        conda install flake8
        # stop the build if there are Python syntax errors or undefined names
        conda run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        conda run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Predict
      run: |
        conda run python 4-inference.py
      env:
        GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}
        GITHUB_ACTOR: ${{ github.repository_owner }}
